blogData_train <- read.csv("E:/kamagyana/Computing/DARET/Assignments/blogData_train.csv", header=FALSE, stringsAsFactors=FALSE)
View(blogData_train)
head(blogData_train)
colnames(blogData_train)[c(51,52,53,54,55,56,57,58,59,60)] <- c("tcbbt","l24cbbt","48-24cbbt","cf24apbbt","cdif4824","tlbbt","l24lbbt","48-24lbbt","lf24apbbt","ldif4824")
colnames(blogData_train)
colnames(blogData_train)[c(61,62)] <- c("bt-pt","lpt")
colnames(blogData_train)[c(277,278,279,280,281)] <- c("npp","mincnpp","maxcnpp","avcnpp","cnextbbt")
colnames(blogData_train)
name <- c("mean_","sd_","min_","max_","med_")
colnames(blogData_train)[c(1,2,3,4,5)] <- paste(name,colnames(blogData_train)[51])
colnames(blogData_train[c(1,2,3,4,5)])
colnames(blogData_train)[c(6,7,8,9,10)] <- paste(name,colnames(blogData_train)[52])
colnames(blogData_train)[c(11,12,13,14,15)] <- paste(name,colnames(blogData_train)[53])
colnames(blogData_train)[c(16,17,18,19,20)] <- paste(name,colnames(blogData_train)[54])
colnames(blogData_train)[c(21,22,23,24,25)] <- paste(name,colnames(blogData_train)[55])
colnames(blogData_train)[c(26,27,28,29,30)] <- paste(name,colnames(blogData_train)[56])
colnames(blogData_train)[c(31,32,33,34,35)] <- paste(name,colnames(blogData_train)[57])
colnames(blogData_train)[c(36,37,38,39,40)] <- paste(name,colnames(blogData_train)[58])
colnames(blogData_train)[c(41,42,43,44,45)] <- paste(name,colnames(blogData_train)[59])
colnames(blogData_train)[c(46,47,48,49,50)] <- paste(name,colnames(blogData_train)[60])
colnames(blogData_train)
head(blogData_train)sum(is.na(blogData_train))
colnames(blogData_train)[c(263,264,265,266,267,268,269)] <- c("Monbt","Tuebt","Wedbt","Thubt","Fribt",'Satbt',"Sunbt")
colnames(blogData_train)[c(270,271,272,273,274,275,276)] <- c("Monpt","Tuept","Wedpt","Thupt","Fript","Satpt","Sunpt")
colnames(blogData_train)
colnames(blogData_train)[c(63:262)] <- c(paste0("Word",c(seq(1:200))))
colnames(blogData_train)
regdata <- cbind(blogData_train[c(1,6,11,16,21,26,31,36,41,46,c(51:62),277,280,281)])
regword <- cbind(blogData_train[c(63:262,281)])
regday <- cbind(blogData_train[c(263:276,281)])
cor(regdata)
save.image("E:/kamagyana/Computing/DARET/R-code-submissions/Asst14.1.RData")
sum(is.na(blogData_train))
summary(regdata)
summary(regdata)
plot(regdata$tcbbt,regdata$cnextbbt)
plot(regdata$cnextbbt,regdata$tcbbt)
plot(regdata$cnextbbt,regdata$l24cbbt)
plot(regdata$cnextbbt,regdata$`48-24cbbt`)
plot(x=regdata$`48-24cbbt`,y=regdata$cnextbbt)
plot(x=regdata$tcbbt,y=regdata$cnextbbt)
plot(x=regdata$l24cbbt,y=regdata$cnextbbt)
plot(x=regdata$cf24apbbt,y=regdata$cnextbbt)
plot(x=regdata$tlbbt,y=regdata$cnextbbt)
plot(x=regdata$l24lbbt,y=regdata$cnextbbt)
plot(x=regdata$`48-24lbbt`,y=regdata$cnextbbt)
plot(x=regdata$lf24apbbt,y=regdata$cnextbbt)
plot(x=regdata$ldif4824,y=regdata$cnextbbt)
plot(x=regdata$`bt-pt`,y=regdata$cnextbbt)
plot(x=regdata$lpt,y=regdata$cnextbbt)
plot(x=regdata$npp,y=regdata$cnextbbt)
plot(x=regdata$avcnpp,y=regdata$cnextbbt)
cor(regdata)
library(corrplot)
corrplot(cor(regdata),type="full","circle")
regday <- mutate(regday, daybt = ifelse(Monbt==1,"Monday",ifelse(Tuebt==1,"Tuesday",ifelse(Wedbt==1,"Wednesday",ifelse(Thubt==1,"Thursday",ifelse(Fribt==1,"Friday",ifelse(Satbt==1,"Saturday",ifelse(Sunbt==1,"Sunday","NA"))))))))
head(regday)
regday <- mutate(regday, daypt = ifelse(Monpt==1,"Monday",ifelse(Tuept==1,"Tuesday",ifelse(Wedpt==1,"Wednesday",ifelse(Thupt==1,"Thursday",ifelse(Fript==1,"Friday",ifelse(Satpt==1,"Saturday",ifelse(Sunpt==1,"Sunday","NA"))))))))
head(regday)
afit1 <-aov(regday$cnextbbt~regday$daybt)
summary(afit1)
TukeyHSD(afit1)
afit2 <- aov(regday$cnextbbt~regday$daypt)
summary(afit2)
TukeyHSD(afit2)
afit3 <- aov(regdata$`mean_ cf24apbbt`~regday$daypt)
summary(afit3)
TukeyHSD(afit3)
z <- (40-(mean(regdata$tcbbt)))/((sd(regdata$tcbbt))/(sqrt(length(regdata$tcbbt))))
pnorm(z,lower.tail=FALSE)
model1 <- lm(cnextbbt~.,data=regdata)
summary(model1)
AIC(model1)




